class WireGuardProfile {
  static const String defaultAddress = '10.5.0.2/16';
  static const List<String> defaultDnsServers = <String>[
    '103.86.96.100',
    '103.86.99.100',
  ];
  static const String defaultAllowedIps = '0.0.0.0/0, ::/0';
  static const int defaultPort = 51820;
  static const int defaultPersistentKeepalive = 25;

  static String build({
    required String privateKey,
    required String publicKey,
    required String endpointIp,
    required String hostname,
    List<String> dnsServers = defaultDnsServers,
    String address = defaultAddress,
    int port = defaultPort,
    int persistentKeepalive = defaultPersistentKeepalive,
  }) {
    final safePrivateKey = privateKey.trim();
    final safePublicKey = publicKey.trim();
    final safeEndpointIp = endpointIp.trim();
    final safeHostname = hostname.trim();
    final safeDns = dnsServers
        .map((dns) => dns.trim())
        .where((dns) => dns.isNotEmpty)
        .toList();

    final buffer = StringBuffer()
      ..writeln('# Generated by NordAccess')
      ..writeln('# Server: $safeHostname')
      ..writeln('[Interface]')
      ..writeln('PrivateKey = $safePrivateKey')
      ..writeln('Address = $address');

    if (safeDns.isNotEmpty) {
      buffer.writeln('DNS = ${safeDns.join(', ')}');
    }

    buffer
      ..writeln()
      ..writeln('[Peer]')
      ..writeln('PublicKey = $safePublicKey')
      ..writeln('AllowedIPs = $defaultAllowedIps')
      ..writeln('Endpoint = $safeEndpointIp:$port')
      ..writeln('PersistentKeepalive = $persistentKeepalive');

    return buffer.toString();
  }
}
